#!/bin/sh
export PATH="/opt/homebrew/opt/php@8.3/bin:$HOME/.nvm/versions/node/v24.13.0/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"
export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

commitlint --edit "$1"
